name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  #workflow_dispatch: #Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Render using the Render API Key
      - name: Notify Render to Deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"clearCache": false}'
